// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlvnljhcpghefbcyiuru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsdm5samhjcGdoZWZiY3lpdXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0Nzk2NzgsImV4cCI6MjA2NzA1NTY3OH0.i1xzwPNBthpbfbuG3er_38ojH52OixsegadPwHIHzqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});